# Generated by Django 2.1.7 on 2019-05-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Image',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cimage', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Content_Text',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cstr', models.CharField(max_length=500)),
            ],
        ),
    ]
