# Generated by Django 2.2 on 2019-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Image',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cimage', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Text',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('Cstr', models.CharField(max_length=500)),
            ],
        ),
    ]
