# Generated by Django 2.1.7 on 2019-06-01 09:11

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_image',
            name='Cimage',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='img'),
        ),
    ]
