# Generated by Django 2.1.7 on 2019-05-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Seq', models.IntegerField(default=0)),
                ('From', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
                ('ContentID', models.IntegerField(default=0)),
            ],
        ),
    ]
