# Generated by Django 2.1.7 on 2019-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=30)),
                ('Nickname', models.CharField(max_length=20)),
                ('Avator', models.IntegerField(default=-1)),
                ('Description', models.CharField(max_length=40)),
            ],
        ),
    ]
