# Generated by Django 2.1.7 on 2019-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190422_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
