# Generated by Django 2.2 on 2019-04-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='UserID',
            new_name='UserName',
        ),
    ]
