swagger: '2.0'
info:
  description: 'IM_Server API文档'
  version: '1.0.0'
  title: 'IM_Server'
host: '127.0.0.1:8000'
basePath: '/'

tags:
- name: 'account'
  description: '账户'
- name: 'contact'
  description: '联系人'
- name: 'content'
  description: '内容'
- name: 'message'
  description: '消息表'
schemes:
- 'http'

paths:
  /account/register:
    post:
      tags:
      - 'account'
      summary: '注册账户'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '注册信息'
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
  
  /account/login:
    post:
      tags:
      - 'account'
      summary: '登录'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: '登录信息'
        required: true
        schema:
          $ref: '#/definitions/LoginInfo'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
    
    get:
      tags:
      - 'account'
      summary: '获取登录状态'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
  
  /account/logout:
    delete:
      tags:
      - 'account'
      summary: '登出'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
          
  /account/info:
    get:
      tags:
      - 'account'
      summary: '获取账户信息'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnInfo'
        404:
          description: '不能处理的请求'
          
    # put:
    #   tags:
    #   - 'account'
    #   summary: '修改账户全部信息'
    #   parameters:
    #   - in: 'body'
    #     name: 'body'
    #     description: '修改后的账户信息'
    #     required: true
    #     schema:
    #       $ref: '#/definitions/modifyInfo'
    #   consumes:
    #   - 'application/json'
    #   produces:
    #   - 'application/json'
    #   responses:
    #     200:
    #       description: '能够处理的请求'
    #       schema:
    #         $ref: '#/definitions/returnMessage'
    #     404:
    #       description: '不能处理的请求'

  /account/info/avatar:
    post:
      tags:
      - 'account'
      summary: '修改账户头像'
      parameters:
      - in: 'formData'
        name: 'file'
        type: 'file'
        description: '头像'
        required: true
      consumes:
      - 'multipart/form-data'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'

  /account/info/{attr}:
    put:
      tags:
      - 'account'
      summary: '修改账户某项信息'
      parameters:
      - name: 'attr'
        in: 'path'
        required: true
        description: '信息属性'
        type: 'string'
        enum:
        - 'Password'
        - 'Gender'
        - 'Region'
        - 'Nickname'
        - 'Description'
      - in: 'body'
        name: 'body'
        description: '具体信息'
        required: true
        schema:
          $ref: '#/definitions/attrInfo'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'

  /account/info/user/{username}:
    get:
      tags:
      - 'account'
      summary: '获取账户信息'
      parameters:
      - name: 'username'
        in: 'path'
        required: true
        description: '账户名'
        type: 'string'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnInfo'
        404:
          description: '不能处理的请求'

  /account/password:
    PUT:
      tags:
      - 'account'
      summary: '修改密码'
      parameters:
      - in: 'body'
        name: 'body'
        description: '密码信息'
        required: true
        schema:
          $ref: '#/definitions/passworldInfo'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'

  /contact/info:
    get:
      tags:
      - 'contact'
      summary: '获取好友信息'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/contactInfo'
        404:
          description: '不能处理的请求'

  # /contact/add:
  #   post:
  #     tags:
  #     - 'contact'
  #     summary: '添加好友'
  #     parameters:
  #     - in: 'body'
  #       name: 'body'
  #       description: '好友信息'
  #       required: true
  #       schema:
  #         $ref: '#/definitions/addInfo'
  #     consumes:
  #     - 'application/json'
  #     produces:
  #     - 'application/json'
  #     responses:
  #       200:
  #         description: '能够处理的请求'
  #         schema:
  #           $ref: '#/definitions/returnMessage'
  #       404:
  #         description: '不能处理的请求'
          
  /contact/delete:
    post:
      tags:
      - 'contact'
      summary: '删除好友'
      parameters:
      - in: 'body'
        name: 'body'
        description: '好友信息'
        required: true
        schema:
          $ref: '#/definitions/addInfo'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
  
  /content/text:
    post:
      tags:
      - 'content'
      summary: '发送文字信息'
      parameters:
      - in: 'body'
        name: 'body'
        description: '文字信息'
        required: true
        schema:
          $ref: '#/definitions/contentInfo'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
  
  /content/image:
    post:
      tags:
      - 'content'
      summary: '发送图片信息'
      parameters:
      - in: 'formData'
        name: 'file'
        type: 'file'
        description: '图片文件'
        required: true
      - in: 'body'
        name: 'body'
        description: '其他信息'
        required: true
        schema:
          $ref: '#/definitions/contentInfo'
      # consumes:
      # - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
  
  /content/add:
    post:
      tags:
      - 'content'
      summary: '发送好友请求或是同意好友请求'
      parameters:
      - in: 'body'
        name: 'body'
        description: '用户信息'
        required: true
        schema:
          $ref: '#/definitions/contentAddRequest'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'

  /message/{seq}:
    get:
      tags:
      - 'message'
      summary: '获取信息'
      parameters:
      - name: 'seq'
        in: 'path'
        required: true
        description: '消息seqence'
        type: 'integer'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/messageInfo'
        404:
          description: '不能处理的请求'

  /message/seq:
    get:
      tags:
      - 'message'
      summary: '获取seq信息'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/SeqResponse'
        404:
          description: '不能处理的请求'

    post:
      tags:
      - 'message'
      summary: '更新seq信息'
      consumes:
      - 'application/json'
      produces:
      - 'application/json'
      parameters:
      - in: 'body'
        name: 'body'
        description: 'seq信息'
        required: true
        schema:
          $ref: '#/definitions/SeqRequest'
      responses:
        200:
          description: '能够处理的请求'
          schema:
            $ref: '#/definitions/returnMessage'
        404:
          description: '不能处理的请求'
  
definitions:

  User:
    type: 'object'
    required:
    - 'Username'
    - 'Password'
    properties:
      UserID:
        type: 'integer'
      Username:
        type: 'string'
      Password:
        type: 'string'
      Phone:
        type: 'string'
      Email:
        type: 'string'
      Nickname:
        type: 'string'
      Avatar:
        type: 'integer'
      Description:
        type: 'string'
    xml:
      name: 'User'  
  
  LoginInfo:
    type: 'object'
    required:
    - 'Username'
    - 'Password'
    properties:
      Username:
        type: 'string'
      Password:
        type: 'string'
    xml:
      name: 'LoginInfo'
      
  returnMessage:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
        - 'ok'
        - 'fail'
      msg:
        type: 'string'
    xml:
      name: 'returnMessage'
  
  returnInfo:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
        - 'ok'
        - 'fail'
      msg:
        type: 'string'
      data:
        type: 'object'
        properties:
          # UserID:
          #   type: 'integer'
          Username:
            type: 'string'
          # Phone:
          #   type: 'string'
          # Email:
          #   type: 'string'
          Gender:
            type: 'string'
          Region:
            type: 'string'
          Nickname:
            type: 'string'
          Avatar:
            type: 'string'
          Description:
            type: 'string'
    xml:
      name: 'returnInfo'
  
  modifyInfo:
    type: 'object'
    properties:
      Phone:
        type: 'string'
      Email:
        type: 'string'
      Nickname:
        type: 'string'
      Avatar:
        type: 'integer'
      Description:
        type: 'string'
    xml:
      name: 'modifyInfo'
      
  attrInfo:
    type: 'object'
    properties:
      value:
        type: 'string'

  passworldInfo:
    type: 'object'
    properties:
      old_password:
        type: 'string'
      new_password:
        type: 'string'
    xml:
      name: 'passworldInfo'
  
  contactInfo:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
        - 'ok'
        - 'fail'
      msg:
        type: 'string'
      data:
        type: 'array'
        items:
          type: 'object'
          properties:
            Username:
              type: 'string'
            Friend:
              type: 'string'
    xml:
      name: 'contactInfo'
  
  addInfo:
    type: 'object'
    properties:
      username:
        type: 'string'
    xml:
      name: 'addInfo'
  
  contentInfo:
    type: 'object'
    properties:
      timestamp:
        type: 'string'
      to:
        type: 'string'
    xml:
      name: 'contentInfo'

  contentAddRequest:
    type: 'object'
    properties:
      cid:
        type: 'integer'
      to:
        type: 'string'
      info:
        type: 'string'
    xml:
      name: 'contentAddRequest'
      
  messageInfo:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
        - 'ok'
        - 'fail'
      msg:
        type: 'string'
      data:
        type: 'array'
        items:
          type: 'object'
          properties:
            Username:
              type: 'string'
            Seq:
              type: 'integer'
            From:
              type: 'string'
            Type:
              type: 'string'
            ContentID:
              type: 'integer'
            content:
              type: 'object'
              properties:
                Cid:
                  type: 'string'
                Cstr/Cimage:
                  type: 'string'
                Timestamp:
                  type: 'string'
    xml:
      name: 'messageInfo'

  SeqResponse:
    type: 'object'
    properties:
      status:
        type: 'string'
        enum:
        - 'ok'
        - 'fail'
      msg:
        type: 'string'
      data:
        type: 'integer'

  SeqRequest:
    type: 'object'
    properties:
      seq:
        type: 'integer'
  
externalDocs:
  description: 'api.yaml'
  url: 'http://swagger.io'